const actionTypes = {
    SET_QR_CODE: "SET_QR_CODE",
    FETCH_BULLETIN_BOARD: "FETCH_BULLETIN_BOARD",
    SET_SESSION_ID: "SET_SESSION_ID"
};
const mutationTypes = {
    SET_QR_CODE: "SET_QR_CODE",
    SET_BULLETIN_BOARD: "SET_BULLETIN_BOARD",
    SET_SESSION_ID: "SET_SESSION_ID"
};
const getterTypes = {
    GET_QR_CODE: "GET_QR_CODE",
    GET_BULLETIN_BOARD: "GET_BULLETIN_BOARD",
    GET_BULLETIN_BOARD_URL: "GET_BULLETIN_BOARD_URL",
    GET_BULLETIN_BOARD_REFRESH_INTERVAL: "GET_BULLETIN_BOARD_REFRESH_INTERVAL"
};
export {
    actionTypes, getterTypes, mutationTypes
};