const actionTypes = {
    SET_QR_CODE: "SET_QR_CODE",
    FETCH_BULLETIN_BOARD: "FETCH_BULLETIN_BOARD",
    SET_SESSION_ID: "SET_SESSION_ID",
    SET_K_RAND: "SET_K_RAND"
};
const mutationTypes = {
    SET_QR_CODE: "SET_QR_CODE",
    SET_BULLETIN_BOARD: "SET_BULLETIN_BOARD",
    SET_SESSION_ID: "SET_SESSION_ID",
    SET_K_RAND: "SET_K_RAND"
};
const getterTypes = {
    GET_QR_CODE: "GET_QR_CODE",
    GET_BULLETIN_BOARD: "GET_BULLETIN_BOARD",
    GET_BULLETIN_BOARD_URL: "GET_BULLETIN_BOARD_URL",
    GET_BULLETIN_BOARD_REFRESH_INTERVAL: "GET_BULLETIN_BOARD_REFRESH_INTERVAL",
    GET_K_RAND: "GET_K_RAND",
    GET_SESSION_ID: "GET_SESSION_ID"
};
export {
    actionTypes, getterTypes, mutationTypes
};